### ISSUE TITLE
throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?'

### ISSUE THREAD

**Issue by amanpreet321** [HosseinKarami/fastshell#8]
even after reinstalling it gives the same error

**Comment by HosseinKarami** [comment]
Hi 
try this : 
```
npm install --save-dev gulp-sass
```

**Comment by amanpreet321** [comment]
no luck! still the same error

**Comment by HosseinKarami** [comment]
i just updated Dependencies.
please git clone repository and run ``` npm install ``` again.

![fastshell](https://cloud.githubusercontent.com/assets/1345088/11767515/99d275d4-a1c5-11e5-9619-1f29562f6491.png)

**Comment by amanpreet321** [comment]
hey it works now thanks a lot for the support 
![3021307-inline-fb-thumbsup-printpackaging](https://cloud.githubusercontent.com/assets/5407500/11767954/2222745c-a1e4-11e5-943b-68e0175f3c27.jpg)

**Comment by HosseinKarami** [comment]
Good luck. :+1:
